# Generated by Django 4.1.2 on 2022-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='main.tag', verbose_name='Теги'),
        ),
    ]
