# Generated by Django 4.1.1 on 2022-10-28 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers_users', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions_users', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='in_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_posts', to=settings.AUTH_USER_MODEL, verbose_name='Избранные статьи у пользователей'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_posts', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
